name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      # 1. Setup Android environment first
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create local.properties
        run: |
          echo "sdk.dir=$ANDROID_HOME" > local.properties
          echo "api.key=${{ secrets.API_KEY }}" >> local.properties
          cat local.properties

      # 2. Publish weather-utils to local Maven repo
      - name: Publish weather-utils library
        run: ./gradlew :weather-utils:publishToMavenLocal

      # 3. Verify library was published
      - name: Verify Maven local publication
        run: |
          ls -la ~/.m2/repository/com/zek/weather-utils/1.0.0/
          cat ~/.m2/repository/com/zek/weather-utils/1.0.0/weather-utils-1.0.0.pom

      # 5. Cache Gradle
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.android/build-cache
            ~/.m2/repository  # Cache local Maven repo too
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 6-9. Keep your existing build steps...
      - name: Run Linter
        run: ./gradlew lintDebug --stacktrace --continue

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest --stacktrace --continue

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace --warning-mode all

      - name: Verify APK exists
        run: ls -la app/build/outputs/apk/debug/

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk